@startuml Attack Data Class Struct

title Attack Data Class Struct

class AttackData <<Resource>>{
    == Data ==
    + string lateralVelocitySnapshot
    + Type type
    + float damage
    + float delay
    + int maxLevel
}

class ProjectileData <<AttackData>> {
    == Data ==
    + PackedScene projectile
    + float projectileSpeed
}

class AreaOfEffectData <<AttackData>> {
    == Data ==
    + Mesh areaMesh
    + Shape3D areaColliderShape
    + float lvlUpAreaStepSize
}

AttackData *-- ProjectileData
AttackData *-- AreaOfEffectData

@enduml