@startuml Free_Action_Pickup_Sequence
title Free Action Pickup Sequence

start

:Player gets within **pickup range** \nof a **Free Action**;

:**Free Action** is added to the **Interaction Director's** \nlist of nearby actions;

repeat

    if (Player presses the **Pickup Item** button) then (yes)

    note left
        Come back later and implement 
        this **Press Button** feature.
        For now just Add the action if
        the player has space
    end note

        if (Check if player has picked up \nthis kind of **attack** before) then (yes)

            :Get the slot index for the already equipped action;

            if (Can the equipped action be leveled up?) then (yes)

                :Level up the equipped action;

                :Destroy the **Free Action** object;

                :Update the **player UI**;

                end

            else (no)

            endif

        else (no)

            if (Does the Player have an open **attack slot**) then (yes)

                :Get the first **Free Action's** 
                attack data;

                :Initialize the open **Attack Slot's**
                **Attack Object**;

                :Set the **Attack Slot's** index value;

                :Set the **Attack Slot's** attack data;

                :Initialize the **Attack Slot's** timer;

                :Destroy the **Free Action** object;

                :Update the **player UI**;

                end

            else (no)

                :Inform the player they 
                can't pickup the **Free Action**;

            endif

        endif

    else (no)

    endif

repeat while(Player is within **pickup range**) is (yes) not (no)

:Remove the **Free Action** from the \n**Interaction Director's** list of nearby actions;

end

@enduml