@startuml Interaction Class Structure

title Interaction Class Structure

class InteractionDirector <<Node3D>>{
    == Data ==
    .. Public ..
    + string interactionDataPath
    .. Protected ..
    # Area3D hitBoxDir
    # CollisionShape3D hitBoxShape
    # Timer takeDamageTimer
    # PackedScene damageLabel
    # float currentHealth
    .. Private ..
    - InteractionData interactionData

    == Methods ==
    .. Public ..
    + _Ready() : void
    + GetInteractionData() : InteractionData
    + TickHealth() : void
    .. Protected ..
    # DisplayDamageValue() : void
    # LoadInteractionData() : void
    # InitHealthData() : void
    # BeginAoEDamageSequence() : void
    # ProjectileDamageSequence() : void
    # CheckIfDead() : void
    # DeathSequence() : void
    .. Private ..
}

class ActiveAoE <<Node>>{
     == Data ==
    .. Public ..
    + float damage
    + Timer delayTimer
    .. Protected ..
    .. Private ..
    - InteractionDirector interDir

    == Methods ==
    .. Public ..
    + ActiveAoE()
    + Destroy() : void
    .. Protected ..
    .. Private ..
    - TickInteractionDirHealth() : void
}

class PlayerInteractionDirector {
    == Data ==
    .. Public ..
    + int maxAttackCount
    .. Protected ..
    # PlayerInventoryDirector inventoryDir
    # PlayerObjectPickup pickupArea
    .. Private ..
    - PlayerInteractionData interactionData

    == Methods ==
    .. Public ..
    + _Ready() : void
    + GetInteractionData() : PlayerInteractionData
    + IsActionAlreadyEquipped() : int
    + IsPlayerMaxedOutOnAttacks() : bool
    + LevelUpEquippedAction() : bool
    + EquipNewAttack() : void
    .. Protected ..
    # LoadInteractionData() : void
    .. Private ..
}

class NPCInteractionDirector {
    == Data ==
    .. Public ..
    .. Protected ..
    .. Private ..
    - NPCInteractionData interactionData

    == Methods ==
    .. Public ..
    + _Ready() : void
    + GetInteractionData() : NPCInteractionData
    .. Protected ..
    # LoadInteractionData() : void
    .. Private ..
}

class EnemeyInteractionDirector {
    == Data ==
    .. Public ..
    .. Protected ..
    .. Private ..
    - EnemyInteractionData interactionData
    - Node parentNode

    == Methods ==
    .. Public ..
    + _Ready() : void
    + GetInteractionData() : EnemyInteractionData
    .. Protected ..
    # LoadInteractionData() : void
    # DeathSequence() : void
    .. Private ..
    - GetParentNode() : void
}

InteractionDirector *- ActiveAoE
InteractionDirector <|-- PlayerInteractionDirector
InteractionDirector <|-- NPCInteractionDirector
NPCInteractionDirector <|-- EnemeyInteractionDirector

@enduml