@startuml Movement Class Structure

title Movement Class Structure

' Method Classes
class MovementDirector <<CharacterBody3D>>{
    == Data ==
    .. Public ..
    + string movementDataPath
    .. Protected ..
    # Vector2 lateralVelocitySnapshot
    # float verticalVelocitySnapshot
    # float gravity
    .. Private ..
    - MovementData movementData
    == Methods ==
    .. Public ..
    + _Ready() : void
    + _PhysicsProcess() : void
    + LoadMovementkData() : void
    + GetMass() : float
    .. Protected ..
    .. Private ..
    - ApplyGravity() : void
}

class PlayerMovementDirector{
    == Data ==
    .. Public ..
    .. Protected ..
    .. Private ..
    - PlayerMovementData movementData
	- Vector2 inputDirection
    == Methods ==
    .. Public ..
    + _Ready() : void
    + _PhysicsProcess() : void
    + LoadMovementkData() : void
    + GetMass() : float
    .. Protected ..
    .. Private ..
    - HandleJump() : void
    - HandleBasicLateralMovement() : void
    - HandleDodgeRoll() : void
    - GetGlobalInputDirectionNorm() : Vector3
}

class NPCMovementDirector{
    == Data ==
    .. Public ..
    .. Protected ..
    .. Private ..
    - NPCMovementData movementData
    == Methods ==
    .. Public ..
    + _Ready() : void
    + _PhysicsProcess() : void
    + LoadMovementkData() : void
    + GetMass() : float
    .. Protected ..
    .. Private ..
}

class EnemyMovementDirector {
    == Data ==
    .. Public ..
    .. Protected ..
    .. Private ..
    - EnemyMovementData movementData
    == Methods ==
    .. Public ..
    + _Ready() : void
    + _PhysicsProcess() : void
    + LoadMovementkData() : void
    + GetMass() : float
    .. Protected ..
    .. Private ..
}

MovementDirector *-- PlayerMovementDirector
MovementDirector *-- NPCMovementDirector
NPCMovementDirector *-- EnemyMovementDirector

' Resource Classes
class MovementData <<Resource>> {
    .. Public ..
    + float speed
	+ float acceleration
	+ float friction
	+ float mass
    .. Protected ..
    .. Private ..
}

class PlayerMovementData <<Resource>> {
    .. Public ..
    + float jumpVelocity  
	+ float rotationSpeed
	+ float rotationAcceleration
	+ float mouseSensitivity
	+ float rollSpeed
    .. Protected ..
    .. Private ..
}

class NPCMovementData <<Resource>> {
    .. Public ..
    .. Protected ..
    .. Private ..
}

class EnemyMovementData <<Resource>> {
    .. Public ..
    .. Protected ..
    .. Private ..
}

MovementData *-- PlayerMovementData
MovementData *-- NPCMovementData
NPCMovementData *-- EnemyMovementData

@enduml