@startuml Player Attack Class Structure

title Player Attack Class Structure

class PlayerAttackDirector <<Node3D>>{
    == Data ==
    .. Public ..
    + Timer timer
    + int attackIndex
    + int level
    .. Protected ..
    # Node MainRoot
    # bool debug
    # MeshInstance3D meshInstance
    .. Private ..
    - AttackData data

    == Methods ==
    .. Public ..
    + Timer GetAttackTimer()
    + MeshInstance3D GetMeshInstance()
    + void SetAttackIndex()
    + void InitTimer()
    + void SetData()
    + bool IsDataEmpty()
    + void SetVisuals()
    + void SetColliderInformation()
    + void LevelUpAttack()
    + string GetAttackId()
    + int GetAttackMaxLevel()
    .. Protected ..
    # void UpdateTimerTime()
    # void StartTimer()
    # void CallAttack()
}

class PlayerProjectileAttackDirector {
    == Data ==
    .. Private ..
    - ProjectileData data

    == Methods ==
    .. Public ..
    + void SetData()
    + void LevelUpAttack()
    .. Protected ..
    # void CallAttack()
    .. Private ..
    - void ProjectileSequence()
    - Vector3[] GetProjectileInitVelocities()
}

class PlayerAoEAttackDirector {
    == Data ==
    .. Private ..
    - AreaOfEffectData data
    - Area3D AoEHitBoxDirector
    - CollisionShape3D AoEHitBox

    == Methods ==
    .. Public ..
    + void SetData()
    + void SetVisuals()
    + void SetColliderInformation()
    + void LevelUpAttack()
    .. Protected ..
    # void CallAttack()
    .. Private ..
    - void SetAoEObjects()
}

PlayerAttackDirector <|-- PlayerProjectileAttackDirector
PlayerAttackDirector <|-- PlayerAoEAttackDirector

@enduml