@startuml Player Classes

title Player Classes Diagram

class PlayerMovement {
    == Data ==
    .. Private Data ..
    - PlayerMovementData playerData
    - CharacterBody3D charBody
    - Vector2 lateralVelocitySnapshot
    - Vector2 inputDirection
    - float verticalVelocitySnapshot
    - float gravity
    .. Public Data ..

    == Methods ==
    .. Private Methods ..
    - ApplyGravity() : void
    - HandleJump() : void
    - HandleBasicLateralMovement() : void
    - HandleDodgeRoll() : void
    - GetGlobalInputDirectionNorm() : Vector3
    .. Public Methods ..
    + _Ready() : void
    + __PhysicsProcess() : void
}

class PlayerMovementData <<Resource>> {
    == Public Data ==
    + float speed
    + float acceleration
    + float friction
    + float jumpVelocity
    + float rotationSpeed
    + float rotationAcceleration
    + float mouseSensitivity
    + float rollSpeed
    + float mass
    + float gravity
}

class PlayerData {
    == Public ==
    + PlayerMovementData movementData
}

@enduml