@startuml Player Object

title Player Object Diagram

object "Player Director" as Player

object "Movement Director" as Movement
object "Camera Director" as CameraDir
object "Data Director" as Data
object "Visual Director" as Visual
object "Collider" as Collider
object "Camera 3D" as Camera
object "UI Director" as UIDir
object "Animation Director" as Animation
object "Mesh Director" as Mesh
object "Player Scene Director" as SceneDir
object "Quit Game Timer" as QuitTimer

Player : Type = CharacterBody3D
Movement : Type = Node3D
CameraDir : Type = Node3D
Data : Type = Node3D
Visual : Type = Node3D
Collider : Type = CollisionShape3D
Camera : Type = Camera3D
Animation : Type = AnimationPlayer
Mesh : Type = MeshInstance3D
SceneDir : Type = Node3D
QuitTimer : Type = Timer

Player *-- Movement
Player *-- CameraDir
Player *-- Data
Player *-- Visual
Player *-- Collider
CameraDir *-- Camera
Camera *-- UIDir
Visual *-- Animation
Visual *-- Mesh
Player *-- SceneDir
SceneDir *-- QuitTimer

@enduml